import type { Metadata } from "next";
import "./globals.css";
import { AnimatePresence } from "framer-motion";
import { dmsans } from "@/utils/fonts";
// import { GoogleAnalytics } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "Shelcia Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Topbar /> */}
      <AnimatePresence mode="wait" initial={false}>
        <body className={dmsans.className}>{children}</body>
      </AnimatePresence>
    </html>
  );
}
