import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { AnimatePresence } from "framer-motion";
// import Topbar from "@/components/common/Topbar";

// const inter = Inter({ subsets: ["latin"] });

const dmsans = DM_Sans({ subsets: ["latin"] });
export const calSans = localFont({
  src: "../assets/cal-sans/CalSans-SemiBold.woff2",
});

export const metadata: Metadata = {
  title: "Shelcia Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Topbar /> */}
      <AnimatePresence mode="wait" initial={false}>
        <body className={dmsans.className}>{children}</body>
      </AnimatePresence>
    </html>
  );
}
