export const experience = [
  {
    name: "NASDAQ",
    designation: "Senior Software Developer",
    year: "April 2022 - Present",
    // desc: "Developing new UI components and maintaining nasdaq.com",
    desc: "I am working on building new UI components and API integrations for nasdaq.com. I optimize and maintain the codebase for the updated pages. I am also involved in building payment interfaces for monetized articles. I have participated in multiple hackathons within the organization and was greatly lauded for representing the Bangalore branch at global level.",
    skills: ["JavaScript", "Drupal", "Content Management Systems"],
    date: "April 2022",
  },
  {
    name: "Hire All Infotech",
    designation: "Front End Developer",
    year: "May 2021 - April 2022",
    desc: "I worked as a Front End Developer designing UI and developing it from scratch. Ours is a small team working on a Job Recruitment portal paving the way for easier onboarding. I have worked on optimizing the company website performance from 50% to 93%. I had developed an assessment tool with proctoring enabled, a dashboard to enable all these features and all the User interface.",
    // desc: "Designing Team's product UI and developing it from Scratch",
    skills: [
      "ReactJS",
      "Bootstrap",
      "SpringBoot",
      "JavaScript",
      "AdobeXD",
      "Figma",
    ],
    date: "May 2021",
  },
  {
    name: "B. Tech Graduation",
    designation: "GPA 8.5",
    year: "May 2017 - July 2021",
    desc: "Bachelor of Technology at Indian Institute of Information Technology Design and Manufacturing, Chennai",
    skills: [
      "Human Computer Interface",
      "Database Management System",
      "Data Structures and Algorithm",
      "Computational Engineering",
      "Engineering Entrepreneurship",
    ],
    date: "May 2021",
  },
  {
    name: "NYX Wolves Private Limited",
    designation: "Full Stack Developer",
    year: "Nov 2020 - May 2021",
    desc: "I worked as a Full-stack Developer actively designing and developing as per clients requirements. I was involved in over 10 projects in which I majorly/ solely developed 4 projects. I was also actively involved in the deployment process using Docker containers in AWS.",
    // desc: "Working alongside the designer team implementing the designs, also developing custom solutions to address team necessities.",
    skills: ["ReactJS", "MongoDB", "NodeJS", "Docker", "Keycloak"],
    date: "November 2020",
  },
  {
    name: "Guvi Geeks Private Limited",
    designation: "Software Developer Intern",
    year: "Oct 2020 - Dec 2020",
    desc: "As a website developer, I worked with Javascript and Jquery, focusing on rebuilding different portals and creating new pages as per the requirement.",
    // desc: "Part of 5 members taking care of the new version of Edu Tutor web app; Implementing new design;",
    skills: ["HTML5", "CSS3", "JavaScript", "jQuery"],
    date: "October 2020",
  },
  {
    name: "Solera Life Scienece",
    designation: "Web Developer Intern",
    year: "May 2020 - Oct 2020",
    desc: "I worked as a website developer and designer, building products in ADOBE XD. One of the projects was to work on an E-commerce app for Pharma products and another project was based on building a chatbot interface with NLP implemented. This would in turn reduce the company costs in customer handling.",
    // desc: "I worked as a website developer and designer building a couple of products. One of them is an E-commerce app for Pharma products and another product is based on building chatbot interface (familiar example DialogueFlow).",
    skills: [
      "ReactJS",
      "NodeJS",
      "JavaScript",
      "AdobeXD",
      "Figma",
      "Dialogueflow",
    ],
    date: "May 2020",
  },
  {
    name: "NUS Computing",
    designation: "Academic Intern",
    year: "May 2019 - June 2019",
    desc: "I was involved in an academic internship in Singapore. Over there I had a handful of experience in networking architecture, building security-focused on IoT systems. I built two projects, one was based IOT based Disaster management system under the guidance of Professor Tan Wee Kek and the second project was based on visualising data in the admin Dashboard under the guidance of Mr Shanthanu Pandey, Hewlett Packard.",
    skills: ["IOT", "Robotics", "HTML", "CSS"],
    date: "May 2019",
  },
  {
    name: "Graduted High School",
    designation: "  Score: 93.8%",
    year: "May 2017",
    desc: "Graduated in PCM with Major in Computer Science",
    skills: ["Data Structures", "My SQL"],
    date: "May 2017",
  },
];
