export const experience = [
  {
    name: "iSchool - University of Wisconsin-Madison",
    designation: "Master of Science in Information",
    year: "August 2023 - Present",
    desc: "Learning and Exploring. UW Makeathon Winner (https://making.engr.wisc.edu/makeathon/)",
    skills: [
      "User Experience",
      "Human Computer Interaction",
      "Frontend Development",
    ],
    date: "August 2023",
    timeline: "Aug'23 - Dec'24",
  },
  {
    name: "NASDAQ",
    designation: "Senior Software Developer",
    year: "April 2022 - August 2023",
    desc: "Engaged in developing new UI components and integrating APIs for nasdaq.com. My responsibilities encompass codebase optimization and maintenance for the revised pages. Additionally, I was actively engaged in constructing payment interfaces for monetized articles. I have also participated in numerous hackathons within the organization, where I earned recognition for my contributions. Notably, I was commended for representing the Bangalore branch at a global level.",
    skills: ["JavaScript", "Drupal", "Content Management Systems"],
    date: "April 2022",
    timeline: "Apr'22 - Aug'23",
  },
  {
    name: "Hire All Infotech",
    designation: "Front End Developer",
    year: "May 2021 - April 2022",
    desc: "I served as a Front-End Developer, responsible for both UI design and its ground-up development. I was part of a small team dedicated to creating a Job Recruitment portal aimed at streamlining the onboarding process. Notably, I successfully optimized the performance of the company website, increasing its efficiency from 50% to 93%. Furthermore, I designed and developed an assessment tool with proctoring capabilities, along with a comprehensive dashboard to facilitate these functions, all while maintaining the user interface.",
    skills: [
      "ReactJS",
      "Bootstrap",
      "SpringBoot",
      "JavaScript",
      "AdobeXD",
      "Figma",
    ],
    date: "May 2021",
    timeline: "May'21 - Apr'22",
  },
  {
    // name: "B. Tech Graduation",
    // designation: "GPA 8.5",
    // year: "May 2017 - July 2021",
    // desc: "Bachelor of Technology at Indian Institute of Information Technology Design and Manufacturing, Chennai",

    name: "Indian Institute of Information Technology Design and Manufacturing, Chennai",
    year: "May 2017 - July 2021",
    designation: "Bachelor of Technology",
    desc: "Pursued Smart Manufacturing Engineering as a Women in Tech Organizer at IIITDM Kancheepuram, where I also held the roles of Robotics Club Secretary and Sponsorship Secretary. I maintained a GPA of 8.5/10.",

    skills: [
      "Human Computer Interface",
      "Database Management System",
      "Data Structures and Algorithm",
      "Computational Engineering",
      "Engineering Entrepreneurship",
    ],
    date: "May 2021",
    timeline: "Jul'17 - Jul'21",
  },
  {
    name: "NYX Wolves Private Limited",
    designation: "Full Stack Developer",
    year: "Nov 2020 - May 2021",
    desc: "I worked as a Full-stack Developer, actively involved in designing and developing solutions according to client requirements. Throughout this role, I contributed to over 10 projects, with a significant or sole involvement in the development of four of these projects. Additionally, I played a key role in the deployment process, utilizing Docker containers on the AWS platform.",
    // desc: "Working alongside the designer team implementing the designs, also developing custom solutions to address team necessities.",
    skills: ["ReactJS", "MongoDB", "NodeJS", "Docker", "Keycloak"],
    date: "November 2020",
    timeline: "Nov'20 - May'21",
  },
  {
    name: "Guvi Geeks Private Limited",
    designation: "Software Developer Intern",
    year: "Oct 2020 - Dec 2020",
    desc: "I specialized in JavaScript and jQuery as a website developer. My work involved revitalizing portals with enhanced functionality and crafting new, dynamic web pages tailored to project needs. This included optimizing performance, user experience, and aligning with industry standards.",
    // desc: "Part of 5 members taking care of the new version of Edu Tutor web app; Implementing new design;",
    skills: ["HTML5", "CSS3", "JavaScript", "jQuery"],
    date: "October 2020",
    timeline: "Oct'20 - Dec'21",
  },
  {
    name: "Solera Life Science",
    designation: "Web Developer Intern",
    year: "May 2020 - Oct 2020",
    desc: "I worked as a website developer and designer, creating products using Adobe XD. I was involved in two projects: the first project focused on developing an E-commerce app for pharmaceutical products, while the second project centered around building a chatbot interface with implemented NLP. This implementation aimed to reduce company costs associated with customer handling.",
    // desc: "I worked as a website developer and designer building a couple of products. One of them is an E-commerce app for Pharma products and another product is based on building chatbot interface (familiar example DialogueFlow).",
    skills: [
      "ReactJS",
      "NodeJS",
      "JavaScript",
      "AdobeXD",
      "Figma",
      "Dialogueflow",
    ],
    date: "May 2020",
    timeline: "May'20 - Oct'20",
  },
  {
    name: "NUS Computing",
    designation: "Academic Intern",
    year: "May 2019 - June 2019",
    desc: "I participated in an academic internship in Singapore where I gained valuable experience in networking architecture and focused on building security for IoT systems. During my time there, I completed two projects. The first project involved creating an IoT-based disaster management system under the guidance of Professor Tan Wee Kek. The second project centered around visualizing data on the admin dashboard and was conducted under the guidance of Mr. Shanthanu Pandey from Hewlett Packard.",
    skills: ["IOT", "Robotics", "HTML", "CSS"],
    date: "May 2019",
    timeline: "May'19 - Jun'19",
  },
  // {
  //   name: "Maharishi Vidya Mandir",
  //   designation: "Graduted High School",
  //   year: "May 2017",
  //   desc: "Score: 93.8% - Graduated in PCM with Major in Computer Science",
  //   skills: ["Data Structures", "My SQL"],
  //   date: "May 2017",
  // },
];
