import MockerMockup from "../assets/images/mocker.png";
import { Project } from "@/types";

export const featuredProjects: Project[] = [
  {
    id: "mocker",
    name: "Mocker",
    image: MockerMockup,
    desc: "Generate mockup data for testing and prototyping",
    techstack: ["React", "NodeJS", "Material UI", "FakerJs"],
    deploy: true,
    forks: 19,
    stars: 12,
    deployment: "https://mocker-gen.netlify.app/",
    code: "https://github.com/shelcia/mocker",
  },
  {
    id: "socialgram",
    name: "Socialgram",
    image: MockerMockup,
    desc: "Seamless Social Website",
    techstack: ["React", "NodeJS", "Material UI", "FakerJs"],
    deploy: true,
    forks: 19,
    stars: 12,
    deployment: "https://mocker-gen.netlify.app/",
    code: "https://github.com/shelcia/mocker",
  },
  // {
  //   id: "bloggram",
  //   name: "Bloggram",
  //   image: MockerMockup,
  //   desc: "Write, Read and Share Blogs",
  //   techstack: ["React", "NodeJS", "Material UI", "FakerJs"],
  //   deploy: true,
  //   forks: 19,
  //   stars: 12,
  //   deployment: "https://mocker-gen.netlify.app/",
  //   code: "https://github.com/shelcia/mocker",
  // },
  {
    id: "dynamic-portfolio",
    name: "Dynamic Portfolio",
    image: MockerMockup,
    desc: "Build websites by filling up forms",
    techstack: ["React", "NodeJS", "Material UI", "FakerJs"],
    deploy: true,
    forks: 19,
    stars: 12,
    deployment: "https://mocker-gen.netlify.app/",
    code: "https://github.com/shelcia/mocker",
  },
];
